version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - gitea-data:/data
    ports:
      - "3000:3000"  # Web UI
      - "2222:22"    # SSH

volumes:
  gitea-data:
